name: Publish the WebHID demo to pages

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  publish-demo:
    name: Publish demo to Github Pages
    runs-on: ubuntu-latest
    continue-on-error: false
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Prepare build
        run: |
          yarn install
          yarn build
        env:
          CI: true
      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packages/webhid-demo/dist
